apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repository-secret
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: repository-secret
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: https://{{ .Values.gitAddress }}
      data:
        password: "{{`{{ .token }}`}}"
        username: "root"
  data:
  - secretKey: token
    remoteRef:
      key: gitlab
      property: token
